require("dotenv").config();
const { MongoClient } = require("mongodb");

const product_En_forbathroom = require("./forbathroom/en_forbathroom.json");
const product_Ru_forbathroom = require("./forbathroom/ru_forbathroom.json");
const product_De_forbathroom = require("./forbathroom/de_forbathroom.json");
const product_Fr_forbathroom = require("./forbathroom/fr_forbathroom.json");
const product_It_forbathroom = require("./forbathroom/it_forbathroom.json");

const product_En_forhome = require("./forhome/en_forhome.json");
const product_Ru_forhome = require("./forhome/ru_forhome.json");
const product_De_forhome = require("./forhome/de_forhome.json");
const product_Fr_forhome = require("./forhome/fr_forhome.json");
const product_It_forhome = require("./forhome/it_forhome.json");

const product_En_forhotels = require("./forhotels/en_forhotels.json");
const product_Ru_forhotels = require("./forhotels/ru_forhotels.json");
const product_De_forhotels = require("./forhotels/de_forhotels.json");
const product_Fr_forhotels = require("./forhotels/fr_forhotels.json");
const product_It_forhotels = require("./forhotels/it_forhotels.json");

const product_En_forkids = require("./forkids/en_forkids.json");
const product_Ru_forkids = require("./forkids/ru_forkids.json");
const product_De_forkids = require("./forkids/de_forkids.json");
const product_Fr_forkids = require("./forkids/fr_forkids.json");
const product_It_forkids = require("./forkids/it_forkids.json");

async function seedData() {
  const uri = process.env.DATABASE_URL; // Замените на вашу строку подключения MongoDB
  
  const client = new MongoClient(uri);

  try {
    await client.connect();
    const database = client.db("shop-internet-main-db-08025b90a17"); // Замените на имя вашей базы данных
    // const database = client.db("shop"); 
    const collection = database.collection("products"); // Замените на имя коллекции

    const deleted = await collection.deleteMany({});

    
    //   {
    //     title: "CreamColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500214895.webp"],
    //     productCode: 1500214895,
    //     subCategory: "for-bathroom",
    //     price: 20,
    //     description: [
    //       "100% Cotton",
    //       "Bath towel: 90x150 cm, 1 pc",
    //       "90x150 cm, in a PP bag",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 20 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavoite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "20",
    //         color: ["cream"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "PowderColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500214754.webp"],
    //     productCode: 1500214754,
    //     subCategory: "for-bathroom",
    //     price: 27,
    //     description: [
    //       "100% Cotton",
    //       "Set of mats 60x100 cm 1 pc",
    //       "50x60 CM 1 шт",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 27 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "27",
    //         color: ["powder"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "SkyColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500217928.webp"],
    //     productCode: 1500217928,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Cotton",
    //       "Family set",
    //       "Men's bathrobe",
    //       "Women's bathrobe",
    //       "Bath towels, set of 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "148",
    //         color: ["sky"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "AnthraciteColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Cotton",
    //       "Women's bathrobe",
    //       "Bath towels, set of 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "57",
    //         color: ["anthracite"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "PinkColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Cotton",
    //       "Women's bathrobe",
    //       "Bath towels, set of 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "57",
    //         color: ["anthracite"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "AnthraciteColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500217925002.webp"],
    //     productCode: 1500217925002,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Cotton",
    //       "Family set",
    //       "Men's bathrobe",
    //       "Women's bathrobe",
    //       "Bath towels, set of 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "148",
    //         color: ["sky"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MultiColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "48",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MintColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "48",
    //         color: ["mint"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "LavenderColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500201668001.webp"],
    //     productCode: 1500201668001,
    //     subCategory: "for-bathroom",
    //     price: 130,
    //     description: [
    //       "100% Cotton",
    //       "Family set",
    //       "Men's bathrobe",
    //       "Women's bathrobe",
    //       "Bath towels, set of 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "130",
    //         color: ["lavender"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "GreyColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500215665.webp"],
    //     productCode: 1500215665,
    //     subCategory: "for-bathroom",
    //     price: 50,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "50",
    //         color: ["mint"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MultiColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500216663.webp"],
    //     productCode: 1500216663,
    //     subCategory: "for-bathroom",
    //     price: 43,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "43",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CreamColor",
    //     lang: "en",
    //     image: ["/img/productsImageBathroom/1500215673.webp"],
    //     productCode: 1500215673,
    //     subCategory: "for-bathroom",
    //     price: 107,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "43",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },

    //   {
    //     title: "CremeFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500214895.webp"],
    //     productCode: 1500214895,
    //     subCategory: "for-bathroom",
    //     price: 20,
    //     description: [
    //       "100% Baumwolle",
    //       "Badetuch: 90x150 cm, 1 Stk",
    //       "90x150 cm, in einer PP-Tasche",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 20 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "20",
    //         color: ["creme"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "PuderFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500214754.webp"],
    //     productCode: 1500214754,
    //     subCategory: "for-bathroom",
    //     price: 27,
    //     description: [
    //       "100% Baumwolle",
    //       "Set aus Matten 60x100 cm 1 Stk",
    //       "50x60 cm 1 Stk",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 27 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "27",
    //         color: ["puder"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "HimmelFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500217928.webp"],
    //     productCode: 1500217928,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Baumwolle",
    //       "Familien-Set",
    //       "Bademantel für Herren",
    //       "Bademantel für Damen",
    //       "Badetücher, Set aus 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Doppel",
    //         price: "148",
    //         color: ["himmel"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "AnthrazitFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Baumwolle",
    //       "Bademantel für Damen",
    //       "Badetücher, Set aus 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "57",
    //         color: ["anthrazit"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "RosaFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Baumwolle",
    //       "Bademantel für Damen",
    //       "Badetücher, Set aus 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "57",
    //         color: ["anthrazit"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "AnthrazitFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500217925002.webp"],
    //     productCode: 1500217925002,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Baumwolle",
    //       "Familien-Set",
    //       "Bademantel für Herren",
    //       "Bademantel für Damen",
    //       "Badetücher, Set aus 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Doppel",
    //         price: "148",
    //         color: ["himmel"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MehrFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Baumwolle", "Bademantel für Damen"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "48",
    //         color: ["mehrfarbig"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MinzFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Baumwolle", "Bademantel für Damen"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "48",
    //         color: ["minze"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "LavendelFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500201668001.webp"],
    //     productCode: 1500201668001,
    //     subCategory: "for-bathroom",
    //     price: 130,
    //     description: [
    //       "100% Baumwolle",
    //       "Familien-Set",
    //       "Bademantel für Herren",
    //       "Bademantel für Damen",
    //       "Badetücher, Set aus 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Doppel",
    //         price: "130",
    //         color: ["lavendel"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "GrauFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500215665.webp"],
    //     productCode: 1500215665,
    //     subCategory: "for-bathroom",
    //     price: 50,
    //     description: ["100% Baumwolle", "Bademantel für Damen"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "50",
    //         color: ["minze"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MehrFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500216663.webp"],
    //     productCode: 1500216663,
    //     subCategory: "for-bathroom",
    //     price: 43,
    //     description: ["100% Baumwolle", "Bademantel für Damen"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "43",
    //         color: ["mehrfarbig"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CremeFarbe",
    //     lang: "de",
    //     image: ["/img/productsImageBathroom/1500215673.webp"],
    //     productCode: 1500215673,
    //     subCategory: "for-bathroom",
    //     price: 107,
    //     description: ["100% Baumwolle", "Bademantel für Damen"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Badezimmertextilien",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Einzel",
    //         price: "43",
    //         color: ["mehrfarbig"],
    //         availability: 0,
    //       },
    //     },
    //   },

    //   {
    //     title: "CouleurCrème",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500214895.webp"],
    //     productCode: 1500214895,
    //     subCategory: "for-bathroom",
    //     price: 20,
    //     description: [
    //       "100% Coton",
    //       "Serviette de bain : 90x150 cm, 1 pc",
    //       "90x150 cm, dans un sac PP",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 20 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "20",
    //         color: ["crème"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurPoudre",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500214754.webp"],
    //     productCode: 1500214754,
    //     subCategory: "for-bathroom",
    //     price: 27,
    //     description: [
    //       "100% Coton",
    //       "Ensemble de tapis 60x100 cm 1 pc",
    //       "50x60 cm 1 pc",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 27 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "27",
    //         color: ["poudre"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurCiel",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500217928.webp"],
    //     productCode: 1500217928,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Coton",
    //       "Ensemble familial",
    //       "Peignoir pour homme",
    //       "Peignoir pour femme",
    //       "Serviettes de bain, ensemble de 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "148",
    //         color: ["ciel"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurAnthracite",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Coton",
    //       "Peignoir pour femme",
    //       "Serviettes de bain, ensemble de 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "57",
    //         color: ["anthracite"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurRose",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Coton",
    //       "Peignoir pour femme",
    //       "Serviettes de bain, ensemble de 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "57",
    //         color: ["anthracite"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurAnthracite",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500217925002.webp"],
    //     productCode: 1500217925002,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Coton",
    //       "Ensemble familial",
    //       "Peignoir pour homme",
    //       "Peignoir pour femme",
    //       "Serviettes de bain, ensemble de 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "148",
    //         color: ["ciel"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurMulticolore",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Coton", "Peignoir pour femme"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "48",
    //         color: ["multicolore"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurMenthe",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Coton", "Peignoir pour femme"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "48",
    //         color: ["menthe"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurLavande",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500201668001.webp"],
    //     productCode: 1500201668001,
    //     subCategory: "for-bathroom",
    //     price: 130,
    //     description: [
    //       "100% Coton",
    //       "Ensemble familial",
    //       "Peignoir pour homme",
    //       "Peignoir pour femme",
    //       "Serviettes de bain, ensemble de 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "130",
    //         color: ["lavande"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurGris",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500215665.webp"],
    //     productCode: 1500215665,
    //     subCategory: "for-bathroom",
    //     price: 50,
    //     description: ["100% Coton", "Peignoir pour femme"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "50",
    //         color: ["menthe"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurMulticolore",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500216663.webp"],
    //     productCode: 1500216663,
    //     subCategory: "for-bathroom",
    //     price: 43,
    //     description: ["100% Coton", "Peignoir pour femme"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "43",
    //         color: ["multicolore"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CouleurCrème",
    //     lang: "fr",
    //     image: ["/img/productsImageBathroom/1500215673.webp"],
    //     productCode: 1500215673,
    //     subCategory: "for-bathroom",
    //     price: 107,
    //     description: ["100% Coton", "Peignoir pour femme"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Textile de salle de bain",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "simple",
    //         title: "Simple",
    //         price: "43",
    //         color: ["multicolore"],
    //         availability: 0,
    //       },
    //     },
    //   },

    //   {
    //     title: "ColoreCrema",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500214895.webp"],
    //     productCode: 1500214895,
    //     subCategory: "for-bathroom",
    //     price: 20,
    //     description: [
    //       "100% Cotton",
    //       "Asciugamano: 90x150 cm, 1 pz",
    //       "90x150 cm, in una busta PP",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 20 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "20",
    //         color: ["cream"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColorePolvere",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500214754.webp"],
    //     productCode: 1500214754,
    //     subCategory: "for-bathroom",
    //     price: 27,
    //     description: [
    //       "100% Cotton",
    //       "Set di tappeti 60x100 cm 1 pz",
    //       "50x60 cm 1 pz",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 27 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "27",
    //         color: ["powder"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreCielo",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500217928.webp"],
    //     productCode: 1500217928,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Cotton",
    //       "Set famiglia",
    //       "Accappatoio per uomo",
    //       "Accappatoio per donna",
    //       "Asciugamani, set di 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "148",
    //         color: ["sky"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreAntracite",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Cotton",
    //       "Accappatoio per donna",
    //       "Asciugamani, set di 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "57",
    //         color: ["anthracite"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreRosa",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Cotton",
    //       "Accappatoio per donna",
    //       "Asciugamani, set di 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "57",
    //         color: ["anthracite"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreAntracite",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500217925002.webp"],
    //     productCode: 1500217925002,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Cotton",
    //       "Set famiglia",
    //       "Accappatoio per uomo",
    //       "Accappatoio per donna",
    //       "Asciugamani, set di 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "148",
    //         color: ["sky"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreMulticolore",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Cotton", "Accappatoio per donna"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "48",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreMenta",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Cotton", "Accappatoio per donna"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "48",
    //         color: ["mint"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreLavanda",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500201668001.webp"],
    //     productCode: 1500201668001,
    //     subCategory: "for-bathroom",
    //     price: 130,
    //     description: [
    //       "100% Cotton",
    //       "Set famiglia",
    //       "Accappatoio per uomo",
    //       "Accappatoio per donna",
    //       "Asciugamani, set di 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "130",
    //         color: ["lavender"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreGrigio",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500215665.webp"],
    //     productCode: 1500215665,
    //     subCategory: "for-bathroom",
    //     price: 50,
    //     description: ["100% Cotton", "Accappatoio per donna"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "50",
    //         color: ["mint"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreMulticolore",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500216663.webp"],
    //     productCode: 1500216663,
    //     subCategory: "for-bathroom",
    //     price: 43,
    //     description: ["100% Cotton", "Accappatoio per donna"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "43",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "ColoreCrema",
    //     lang: "it",
    //     image: ["/img/productsImageBathroom/1500215673.webp"],
    //     productCode: 1500215673,
    //     subCategory: "for-bathroom",
    //     price: 107,
    //     description: ["100% Cotton", "Accappatoio per donna"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "43",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },

    //   {
    //     title: "CreamColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500214895.webp"],
    //     productCode: 1500214895,
    //     subCategory: "for-bathroom",
    //     price: 20,
    //     description: [
    //       "100% Cotton",
    //       "Bath towel: 90x150 cm, 1 pc",
    //       "90x150 cm, in a PP bag",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 20 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "20",
    //         color: ["cream"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "PowderColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500214754.webp"],
    //     productCode: 1500214754,
    //     subCategory: "for-bathroom",
    //     price: 27,
    //     description: [
    //       "100% Cotton",
    //       "Set of mats 60x100 cm 1 pc",
    //       "50x60 CM 1 шт",
    //     ],
    //     rating: { rate: 4.3, feedBackCount: 27 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "27",
    //         color: ["powder"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "SkyColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500217928.webp"],
    //     productCode: 1500217928,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Cotton",
    //       "Family set",
    //       "Men's bathrobe",
    //       "Women's bathrobe",
    //       "Bath towels, set of 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "148",
    //         color: ["sky"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "AnthraciteColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Cotton",
    //       "Women's bathrobe",
    //       "Bath towels, set of 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "57",
    //         color: ["anthracite"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "PinkColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500214900.webp"],
    //     productCode: 1500214900,
    //     subCategory: "for-bathroom",
    //     price: 57,
    //     description: [
    //       "100% Cotton",
    //       "Women's bathrobe",
    //       "Bath towels, set of 2",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "57",
    //         color: ["anthracite"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "AnthraciteColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500217925002.webp"],
    //     productCode: 1500217925002,
    //     subCategory: "for-bathroom",
    //     price: 148,
    //     description: [
    //       "100% Cotton",
    //       "Family set",
    //       "Men's bathrobe",
    //       "Women's bathrobe",
    //       "Bath towels, set of 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "148",
    //         color: ["sky"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MultiColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "48",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MintColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500217912002.webp"],
    //     productCode: 1500217912002,
    //     subCategory: "for-bathroom",
    //     price: 48,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "48",
    //         color: ["mint"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "LavenderColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500201668001.webp"],
    //     productCode: 1500201668001,
    //     subCategory: "for-bathroom",
    //     price: 130,
    //     description: [
    //       "100% Cotton",
    //       "Family set",
    //       "Men's bathrobe",
    //       "Women's bathrobe",
    //       "Bath towels, set of 4",
    //     ],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["double"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "double",
    //         title: "Double",
    //         price: "130",
    //         color: ["lavender"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "GreyColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500215665.webp"],
    //     productCode: 1500215665,
    //     subCategory: "for-bathroom",
    //     price: 50,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "50",
    //         color: ["mint"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "MultiColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500216663.webp"],
    //     productCode: 1500216663,
    //     subCategory: "for-bathroom",
    //     price: 43,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "43",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },
    //   {
    //     title: "CreamColor",
    //     lang: "ru",
    //     image: ["/img/productsImageBathroom/1500215673.webp"],
    //     productCode: 1500215673,
    //     subCategory: "for-bathroom",
    //     price: 107,
    //     description: ["100% Cotton", "Women's bathrobe"],
    //     rating: { rate: 4.8, feedBackCount: 148 },
    //     material: "cotton",
    //     category: "Bathroom textile",
    //     availabileSize: ["single"],
    //     isFavorite: false,
    //     sizes: {
    //       double: {
    //         size: "single",
    //         title: "Single",
    //         price: "43",
    //         color: ["multicolor"],
    //         availability: 0,
    //       },
    //     },
    //   },
    // ];
    const products = [
      ...product_En_forbathroom,
      ...product_Ru_forbathroom,
      ...product_De_forbathroom,
      ...product_Fr_forbathroom,
      ...product_It_forbathroom,

      ...product_En_forhome,
      ...product_Ru_forhome,
      ...product_De_forhome,
      ...product_Fr_forhome,
      ...product_It_forhome,

      ...product_En_forhotels,
      ...product_Ru_forhotels,
      ...product_De_forhotels,
      ...product_Fr_forhotels,
      ...product_It_forhotels,

      ...product_En_forkids,
      ...product_Ru_forkids,
      ...product_De_forkids,
      ...product_Fr_forkids,
      ...product_It_forkids,
    ];
    const result = await collection.insertMany(products);
    console.log(`${result.insertedCount} продуктов было успешно добавлено.`);
  } catch (error) {
    console.error("Ошибка при вставке данных: ", error);
  } finally {
    await client.close();
  }
}

seedData();
